
version: '3.8'

services:
    # for development use
    app:
        build: .
        container_name: app

        volumes:
            - .:/home/node/app
        ports:
            - 3000:3000
        restart: always
        depends_on:
            - redis
            - postgres
        network_mode: host

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6979:6979
        restart: always
        network_mode: host

    # redis_insight:
    #     image: redislabs/redisinsight:latest
    #     container_name: redis_insight
    #     restart: always
    #     ports:
    #         - 8001:8001
   
    
    dbeaver:
        image: dbeaver/cloudbeaver
        container_name: dbeaver
        restart: always
        ports:
            - 80:80
        network_mode: host
        
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        restart: always
        network_mode: host

            
       

   

        
        
