
version: '3.8'

services:
    # for development use
    app:
        build: .
        container_name: app
        ports:
            - 3000:3000
        networks:
            - default
            
    # frontend: 
    
    # backend:

    cache: 
        image: redis/redis-stack-server:latest
        container_name: redis-service
        ports: 
            - 10001:6379
            - 13333:8001
        networks:
            - default

networks:
    default:
        driver: custom-driver-1

    frontend:
        driver: custom-driver-2

    backend:
        driver: custom-driver-3
   


        
        
