
version: '3.8'

networks:
        app_net:
            driver: bridge

        exemple_net:
            driver: bridge

services:
    # for development use
    app:
        build: .
        container_name: app
        ports:
            - 3000:3000

    cache:
        image: redis:latest
        container_name: redis
        restart: always

    redis_insight:
        image: redislabs/redisinsight:latest
        container_name: redis_insight
        restart: always
        ports:
            - 8001:8001
       
            
       

   

        
        
