
version: '3.1'

services:
    # for development use
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    # for development use
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

     # for development use
    redis: 
        image: redis:latest

        
        
